services:
  serena:
    volumes:
     - "D:\\1C:/workspaces/serena//1C"
     - "D:\\Docker\\app:/workspaces/serena//app"
    container_name: serena  
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "${SERENA_PORT:-9121}:9121"  # MCP server port
      - "${SERENA_DASHBOARD_PORT:-24282}:24282"  # Dashboard port (default 0x5EDA = 24282)
    environment:
      - SERENA_DOCKER=1
    command:
      #- "uv run --directory . serena-mcp-server --transport sse --port 9121 --host 0.0.0.0"
      # Add the context for the IDE assistant
      # - "uv run --directory . serena-mcp-server --transport sse --port 9121 --host 0.0.0.0 --context ide-assistant"
      #- "uv run --directory . serena-mcp-server --transport streamable-http --port 9121 --host 0.0.0.0 --context ide-assistant"
      - "uv run --directory . serena-mcp-server --transport streamable-http --port 9121 --host 0.0.0.0"